### ISSUE TITLE
Qual o nome oficial da empresa?

### ISSUE THREAD

**Issue by CampioniMan** [CampioniMan/TCC#11]
Já que o prof. Samuel deseja que uma empresa seja criada para o projeto, precisamos decidir qual será o nome dela.
## Opções de nome
- [ ] 1. The Treasure Hunting
- [ ] 2. The Hunters
- [ ] 3. Danpegis
- [ ] 4. Megafoone
- [ ] 5. Foo Players
- [ ] 6. Multiple Fighters
- [x] 7. Foo Deuh || Foo Del || Foo Deoo
- [ ] 8. Time Treasure
- [ ] 9. C Save the Queen (CSQ)
- [ ] 10. Foo's reality
- [ ] 11. Cofooca
- [ ] 12. Foo Fool

OBS MEMBROS: Adicionem opções conforme acharem boas escolhas.

**Comment by tiagodalloca** [comment]
10.

**Comment by CampioniMan** [comment]
Daniel: 11 e 7.
Thaís: 6 e 7.
Bruno: 7.

**Comment by alexerr400** [comment]
11 ctz

**Comment by emilioCosta** [comment]
8

**Comment by tiagodalloca** [comment]
:poo:

**Comment by camilabbertelli** [comment]
4, 10 ou 12
